baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'NexMorocco '
theme = "nexmorocco"

enableRobotsTXT = true
enableRSS = true

[robotstxt]
    userAgent = "*"
    allow = "/"



[[menus.main]]
name = 'NexMorocco'
pageRef = '/'
weight = 1

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 2


[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 3

[[menus.main]]
name = 'Events'
pageRef = '/events'
weight = 4

[[menus.main]]
name = 'News'
pageRef = '/news'
weight = 5

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 6



