baseURL = 'https://nexmorocco.netlify.app'
languageCode = 'en-us'
title = 'NexMorocco '
theme = "nexmorocco"

[params]
    joinLink = "https://github.com/taha-cmyk/contrib"


enableRobotsTXT = true
enableRSS = true

[robotstxt]
    userAgent = "*"
    allow = "/"




