baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'NexMorocco '
theme = "nexmorocco"

enableRobotsTXT = true
enableRSS = true

[robotstxt]
    userAgent = "*"
    allow = "/"



[[menus.main]]
name = 'NexMorocco'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20


[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 30

[[menus.main]]
name = 'Events'
pageRef = '/events'
weight = 40

[[menus.main]]
name = 'News'
pageRef = '/news'
weight = 50

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 60



